"use client";

import { MessageSquare } from "lucide-react";
import { SectionCard } from "./section-card";

interface InterviewQuestionsProps {
  questions: string[];
  error?: boolean;
  onRetry?: () => void;
}

/**
 * AI Interview Questions — 3–7 tailored questions generated by the AI Engine
 * based on the candidate's resume and job requirements.
 *
 * Requirement 11.8
 */
export function InterviewQuestions({
  questions,
  error = false,
  onRetry,
}: InterviewQuestionsProps) {
  return (
    <SectionCard
      title="AI Interview Questions"
      icon={<MessageSquare className="h-5 w-5" aria-hidden="true" />}
      error={error}
      onRetry={onRetry}
    >
      {questions.length > 0 ? (
        <ol className="space-y-3 list-none" aria-label="Interview questions">
          {questions.map((question, idx) => (
            <li key={idx} className="flex gap-3">
              <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-indigo-50 text-xs font-semibold text-indigo-600">
                {idx + 1}
              </span>
              <p className="text-sm leading-relaxed text-navy pt-0.5">
                {question}
              </p>
            </li>
          ))}
        </ol>
      ) : (
        <p className="text-sm italic text-muted-foreground">
          No interview questions generated yet.
        </p>
      )}
    </SectionCard>
  );
}
